### ISSUE TITLE
Editing a rule: Dialog to choose an action.

### ISSUE THREAD

**Issue by hkohlsaat** [schul-cloud/rights-editor#1]
The hovering dialog  is a modal.

- [x] check out [a vue example modal](https://vuejs.org/v2/examples/modal.html)
- [x] find the example in large part reproduced in src/components/BaseModal, note that we call it Base... because it does not cary any specific content and should server as base. Modify it as necessary by relying on slots to display specific information (see [information on slots in vue](https://vuejs.org/v2/guide/components-slots.html))
- [x] show the modal (also called dialog here) to choose an action type when clicking on the rule's action
- [x] the dialog should show the headline 'Aktion auswählen' or sth alike
- [x] the dialog should show a (scrollable) list of possible action types (descriptions or explanations are not needed here, they will form a follow-up ticket)
- [x] the dialog should show a button saying 'Annehmen' if an action is selected from the list, when the button is clicked the selected action should be entered into the data structure and therefore be visible as the new state of the rule
- [x] the dialog should show a button saying 'Abbrechen' to leave the dialog without changing any rule state

**Comment by odanivan** [comment]
This is completely done right? @hkohlsaat @CarolinGoerke
