### ISSUE TITLE
Unify the way we ask YES/NO questions to the user

### ISSUE THREAD

**Issue by odanivan** [schul-cloud/rights-editor#22]
Whenever we have buttons that communicate binary information and therefore force the user to decide between "yes" or "no" ("Annehmen" or "Abbrechen", "Erlaubt", "Nicht erlaubt"), the way we visualize that in regards to positioning should be equal in all our UI elements. Which of the following options should we choose?

Annehmen ... Abbrechen ....................................................................................................

Abbrechen ... Annehmen .....................................................................................................

....................................................................................................... Abbrechen ... Annehmen

....................................................................................................... Annehmen ... Abbrechen

Annehmen ........................................................................................................... Abbrechen

Abbrechen ............................................................................................................ Annehmen

**Comment by mxrcx** [comment]
Annehmen ........................................................................................................... Abbrechen
Annehmen ... Abbrechen ....................................................................................................

**Comment by odanivan** [comment]
Ja, ich finde auch, dass der Annehmen Button links sein sollte, weil man bei der Variante den kürzesten Mausweg zurücklegt. Abbrechen ist eher ein Sonderfall glaube ich.
