### ISSUE TITLE
Failure of a rule: edit a rule to have a referenced rule for failure

### ISSUE THREAD

**Issue by hkohlsaat** [schul-cloud/rights-editor#6]
The rule type logically can have a reference to another rule, e.g. on failure to comply to one rule this rule could have a reference (called `failure` in the diagram) to a fall-back rule. Make it possible to add such a failure rule to RuleItem (represent the referenced rule by showing another RuleItem and do not introduce a specialized component for this task, so future changes to RuleItem benefit the referenced rule also). Find a clever way to display it. Maybe it is helpful to mimic the structure of the resulting json in the UI (but maybe not - find out).
- [x] implement it

**Comment by odanivan** [comment]
A Permission can have a duty. A Duty can have a consequence. A Prohibition can have a remedy. So this is basically done, right?
