### ISSUE TITLE
Find dynamic mechanism to size the RuleItem (.rule-container)

### ISSUE THREAD

**Issue by hkohlsaat** [schul-cloud/rights-editor#61]
The html class of the RuleItem's root div is `rule-container`. The css for `.rule-container` says
```css
.rule-container {
  width: 1000px;
}
```
Either this rule has no effect (for some reason) so it should be removed or the size is in fact hard-coded to `width: 1000px` which is not dynamic and should be replaced by a set of rules that size the RuleItem to the remaining available space in the RuleEditor it is contained in.

**Comment by odanivan** [comment]
This is done with #65
