### ISSUE TITLE
Add animations to visualize removing/creating a rule

### ISSUE THREAD

**Issue by odanivan** [schul-cloud/rights-editor#7]
**Add small, fast animations just to better visualize some functionality like removing/creating a rule**

When creating a new rule by clicking on a button, maybe scroll down to the newly created rule UI form to give visual feedback that something actually happened. Because as it is now, when the screen is already full with rules, adding them at the bottom can't be noticed/seen. Same thing goes for removing rules. Clicking on the X while there are still a lot of rules left has the following correct though slightly misleading behavior: The next rule gets displayed at the exact same position immediately. It happens so fast in fact, that the user might wonder if anything happened at all. So add a little removing animation here, but nothing too special as we don't want the ui experience to be fast and direct.

**Comment by mxrcx** [comment]
scroll down (to last element in container) after deleting an item works

-> After adding an item: it scrolls down to the vorletzte Element
